### ISSUE TITLE
Error during training

### ISSUE THREAD

**Issue by qwedaq** [Bostoncake/C-VisDiT#2]
Hello I am facing the following error when trying to reproduce the experiments A->C and C->A for OfficeHome dataset. I have trained using the values mentioned in their respective config files. Can you please help me resolve it?

![err3](https://github.com/user-attachments/assets/9a764c8f-93fd-4af0-ab00-5e22442cbda0)

**Comment by Bostoncake** [comment]
Thanks for pointing this out! We have used the `plot_mapping_acc()` method for our analysis experiments in our paper, and we forgot to comment this line out when organizing our code for publication. Just simply get rid of Line 154 in BaseAgent.py will work our for you. We will quickly fix this in our codebase.
